### ISSUE TITLE
License mismatch and suggestions

### ISSUE THREAD

**Issue by xuhdev** [hgraeber/editorconfig-qtcreator#1]
The README file claims it's using LGPLv3, but the LICENSE text is GPLv3 --- you should also include the [LGPL text](https://www.gnu.org/licenses/lgpl-3.0.txt). For example, you can rename the current LICENSE file to gpl.txt, and use the LGPL text to fill in the LICENSE file.

Another issue is that the project is licensed under LGPLv3 (ONLY), however, it is recommended to use LGPLv3+, i.e., "LGPL version 3 or any later version at your option", to avoid future compatibility issues when LGPLv[4567] is born. But any way, this is your choice: you can choose to to be incompatible with future versions of (L)GPL.

The final issue is that it is recommended to add the following header to all source files, according to the [GPL guideline](https://www.gnu.org/licenses/gpl-howto.en.html):

>     This file is part of EditorConfig QtCreator Plugin.
> 
>     EditorConfig QtCreator Plugin is free software: you can redistribute it and/or modify
>     it under the terms of the GNU Lesser General Public License as published by
>     the Free Software Foundation, either version 3 of the License, or
>     (at your option) any later version.
> 
>     EditorConfig QtCreator Plugin is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU Lesser General Public License for more details.
> 
>     You should have received a copy of the GNU Lesser General Public License
>     along with EditorConfig QtCreator Plugin.  If not, see <http://www.gnu.org/licenses/>.

**Comment by hgraeber** [comment]
That's a typo. Originally GPL-3 was intended. I have fixed this now and use the same licenses like most QtCreator plugins. LGPL-3 and LGPL-2.1 are allowed and use with the commercial version of QtCreator is allowed, too. So, in future it will be possible to include the plugin in the QtCreator distribution.
